# Generated by Django 5.1.13 on 2025-10-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de carrito',
                'verbose_name_plural': 'Estados de carrito',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carritos', to='cart.carritoestado')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.carrito')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrito_items', to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Ítem de carrito',
                'verbose_name_plural': 'Ítems de carrito',
            },
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='idx_carrito_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='carritoitem',
            index=models.Index(fields=['carrito'], name='idx_citem_carrito'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_citem_cantidad_gt_0'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'variante')},
        ),
    ]
