# Generated by Django 5.1 on 2025-10-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agregados_carrito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='clics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='compras',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='favoritos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_rel', to='catalog.producto'),
        ),
    ]
