# Generated by Django 5.1 on 2025-11-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_color_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_color_predeterminados', to='catalog.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talle_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_predeterminados', to='catalog.talle', verbose_name='Talle'),
        ),
    ]
