# Generated by Django 5.1 on 2025-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_producto_color_predeterminado_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productovariante',
            name='ck_var_stock_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='productovariante',
            name='ck_var_pc_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='productovariante',
            name='ck_var_pv_gte_0',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen principal'),
        ),
    ]
