# Generated by Django 5.1.13 on 2025-10-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagen')),
                ('button_text', models.CharField(blank=True, default='Ver más', max_length=50, verbose_name='Texto del botón')),
                ('button_url', models.CharField(blank=True, default='/catalog/', max_length=300, verbose_name='Botón URL o ruta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Slide de carrusel',
                'verbose_name_plural': 'Slides de carrusel',
                'ordering': ['order', 'id'],
            },
        ),
    ]
