# Generated by Django 5.1.13 on 2025-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='button_url',
            field=models.CharField(blank=True, default='/catalog/', max_length=300, verbose_name='Botón URL o ruta'),
        ),
    ]
