# Generated by Django 5.1.13 on 2025-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carouselslide_button_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Slide de carrusel', 'verbose_name_plural': 'Slides de carrusel'},
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='button_text',
            field=models.CharField(blank=True, default='Ver más', max_length=50, verbose_name='Texto del botón'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to='carousel/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título'),
        ),
    ]
