# Generated by Django 5.1.13 on 2025-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carouselslide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('contrasenia', models.CharField(db_column='Contrasenia', max_length=255)),
                ('id_rol', models.IntegerField(db_column='ID_Rol', default=2)),
                ('direccion', models.CharField(db_column='Direccion', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('id_estado_usuario', models.IntegerField(db_column='ID_EstadoUsuario', default=1)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
