# Generated by Django 5.1.13 on 2025-10-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de pedido',
                'verbose_name_plural': 'Estados de pedido',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=255)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='orders.pedidoestado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_detalles', to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'indexes': [models.Index(fields=['pedido'], name='idx_pdet_pedido')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_pdet_cantidad_gt_0'), models.CheckConstraint(condition=models.Q(('precio_unitario__isnull', True), ('precio_unitario__gte', 0), _connector='OR'), name='ck_pdet_pu_null_or_gte_0')],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'fecha'], name='idx_pedido_usuario_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_pedido_total_gte_0'),
        ),
    ]
