# Generated by Django 5.1 on 2025-11-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedidotemporal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidotemporal',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Pedido temporal', 'verbose_name_plural': 'Pedidos temporales'},
        ),
    ]
