# Generated by Django 5.1 on 2025-11-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_pedidotemporal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidotemporal',
            options={},
        ),
    ]
